In [32]:

import numpy as np
import pandas as pd

In [56]:

sv = np.genfromtxt("student.txt",delimiter=';',dtype=None ,encoding='utf-16',names=True)

# print(sv)
sinhvien = pd.DataFrame(sv)
# print(sinhvien)

# sinhvien.head(5)
# print()
# sinhvien.tail(5)

# print(sinhvien['ID'])

# print()
# print(sinhvien['Name'].head(5))

# print()
print(sinhvien[['ID','Name']])
print(sinhvien.columns)

          ID              Name
0   16050007   Đặng Phương Anh
1   16051722  Đinh Thị Vân Anh
2   16050014        Đỗ Lan Anh
3   16051723     Kiều Ngọc Ánh
4   16050008       Lê Ngọc Ánh
..       ...               ...
94  16051804   Trần THị Cẩm Tú
95  16051811    Trần Ngọc Xuân
96  17050098    Nguyễn THị Vân
97  16051811    Trần Ngọc Xuân
98  16051811    Trần Ngọc Xuân

[99 rows x 2 columns]
Index(['ID', 'Name', 'BOD', 'Gender', 'Mark', 'Class'], dtype='object')

In [83]:

sv = np.genfromtxt("student.txt",delimiter=';',dtype=None ,encoding='utf-16',names=True)

# print(sv)
sinhvien = pd.DataFrame(sv)

# sinhvien.info()
# sinhvien.describe()
# print("@@@SHAPE@@@")
# sinhvien.shape

# sinhvien.value_counts(dropna=False)
sinhvien['ID'].value_counts()

sinhvien.sort_values(['ID','Name'], ascending=False)

          ID                 Name         BOD Gender Mark           Class
85  17050098       Nguyễn THị Vân  21/09/1999      F    7  QH-2017-E KTPT
90  17050098       Nguyễn THị Vân  21/09/1999      F    7  QH-2017-E KTPT
96  17050098       Nguyễn THị Vân  21/09/1999      F    7  QH-2017-E KTPT
79  17050095        Đào Thu Trinh  08/09/1999      F    3  QH-2017-E KTPT
73  17050090        Nguyễn Anh Tú  09/07/1999      F    9  QH-2016-E KTPT
..       ...                  ...         ...    ...  ...             ...
30        -1  Phùng Thị Bích Hoàn  04/11/1998      M    9  QH-2017-E KTPT
87        -1   Nguyễn Thị Hải Vân  18/09/1998      F    9  QH-2017-E KTPT
49        -1      Nguyễn Thu Ngân  20/08/1998      M    8  QH-2017-E KTPT
47        -1         Nguyễn Hà My  14/02/1997      M    5  QH-2017-E KTPT
26        -1        Hoàng Quý Huy  24/02/1998      F    8  QH-2016-E KTPT

[99 rows x 6 columns]

In [89]:
sv = np.genfromtxt("student.txt",delimiter=';',dtype=None ,encoding='utf-16',names=True)

# print(sv)
sinhvien = pd.DataFrame(sv)

sinhvien[sinhvien['Gender'] == 'M']

          ID                  Name         BOD Gender Mark              Class
12  16050021          Lê Thị Giang  07/09/1998      M       QH-2017-E KINH TẾ
13  16051730         Mai Thị Giang  08/09/1998      M    9     QH-2017-E KTPT
16  16050028  Nguyễn Thị Thúy Hiền  12/03/1998      M    8  QH-2017-E KINH TẾ
18  17050022       Hoàng Minh Hiếu  21/06/1999      M          QH-2016-E KTPT
19  16050021          Lê Thị Giang  07/09/1998      M       QH-2017-E KINH TẾ
20  16051730         Mai Thị Giang  08/09/1998      M    9     QH-2017-E KTPT
23        -1   Phùng Thị Bích Hoàn  04/11/1998      M    9     QH-2017-E KTPT
24  16050038           Đỗ Thị Hồng  20/06/1998      M       QH-2017-E KINH TẾ
25  17050035      Nguyễn Thanh Huệ  12/04/1999      M    7     QH-2016-E KTPT
30        -1   Phùng Thị Bích Hoàn  04/11/1998      M    9     QH-2017-E KTPT
31  16050038           Đỗ Thị Hồng  20/06/1998      M       QH-2017-E KINH TẾ
35        -1       Trương Tuấn Huy  06/04/1998      M    5     QH-2016-E KTPT
43  16050084     Phạm Lê Diệu Linh  21/08/1998      M    6     QH-2016-E KTPT
46  16050091     Trương Hoàng Minh  27/07/1998      M    4     QH-2017-E KTPT
47        -1          Nguyễn Hà My  14/02/1997      M    5     QH-2017-E KTPT
49        -1       Nguyễn Thu Ngân  20/08/1998      M    8     QH-2017-E KTPT
68  16050175       Nông Thanh Thảo  11/10/1998      M    4     QH-2016-E KTPT
69  16051784    Hoàng Thị Thu Thủy  20/10/1998      M    5     QH-2016-E KTPT
71  16050140        Trần Thị Trang  29/12/1998      M    7     QH-2016-E KTPT
80  16051802     Nguyễn Doãn Trung  25/09/1998      M    5     QH-2016-E KTPT
82  16051803       Trần Văn Trường  10/02/1997      M          QH-2016-E KTPT
92  16051802     Nguyễn Doãn Trung  25/09/1998      M    5     QH-2016-E KTPT
93  16051803       Trần Văn Trường  10/02/1997      M          QH-2016-E KTPT

In [252]:



# sinhvien.loc[sinhvien['Gender'] == 'F', ['Name','Gender', 'Class']]
# print(sinhvien.isnull())
# sinhvien.dropna()
# sinhvien['Mark'].fillna('NaN')

sinhvien['Mark'].isnull().sum()

# sinhvien.replace('', np.nan , inplace= True)

99

In [259]:
df = pd.read_csv('student.csv', header=None, sep=";", skiprows=1)
df.columns = ['ID', 'Name', 'BOD', 'Gender', 'Mark', 'Class']
df = pd.DataFrame(df)
df.replace(['F','M'],['Nam','Nữ'], inplace=True)

df['Mark'] = pd.to_numeric(df['Mark'], errors='coerce')


diem_trung_binh = round(np.mean(df['Mark']),1)
# df.head(20)
# df['Mark'].replace(np.nan, diem_trung_binh, inplace=True)

df['Mark'] = df['Mark'].fillna(diem_trung_binh)

df = df.rename(columns={'ID': 'MSSV', 'Name':'Ho_Ten','BOD': 'Ngay_Sinh','Gender':'Gioi_Tinh','Mark': 'Diem','Class': 'Lop',})

df.head(5)

sv_nam = df
sv_nam = sv_nam[sv_nam['Gioi_Tinh'] == 'Nam']
sv_nam = sv_nam.drop(['Ngay_Sinh','Gioi_Tinh','Diem'], axis=1)
sv_nam.tail(50)

sv_nam.to_csv('bth5_sv.csv', encoding='utf-8', index=False, header=True)

new = pd.read_csv('bth5_sv.csv', header=None, skiprows=1)
print(new)

             0                 1                  2
0   16050007.0   Đặng Phương Anh     QH-2016-E KTPT
1   16051722.0  Đinh Thị Vân Anh  QH-2017-E KINH TẾ
2   16050014.0        Đỗ Lan Anh     QH-2017-E KTPT
3   16051723.0     Kiều Ngọc Ánh     QH-2017-E KTPT
4   16050008.0       Lê Ngọc Ánh     QH-2017-E KTPT
..         ...               ...                ...
67  17050098.0    Nguyễn THị Vân     QH-2017-E KTPT
68  16051811.0    Trần Ngọc Xuân     QH-2016-E KTPT
69  16051804.0   Trần THị Cẩm Tú     QH-2016-E KTPT
70  17050098.0    Nguyễn THị Vân     QH-2017-E KTPT
71  16051811.0    Trần Ngọc Xuân     QH-2016-E KTPT

[72 rows x 3 columns]